/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalprojectjava;

/**
 *
 * @author Mira
 */
public class CoffeeStore extends javax.swing.JFrame {

    /**
     * Creates new form CoffeeStore
     */
    public CoffeeStore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenu1 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDisplayCustomer = new javax.swing.JButton();
        btnNewOrder = new javax.swing.JButton();
        btnDisplayOrders = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnDisplayCofee1 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu6.setText("jMenu6");

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COFFEE MANAGEMENT ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 360, 53));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 204));
        jLabel3.setText("Looking for a cozy spot to enjoy a delicious cup of coffee? Look no further than our coffee shop!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 550, 40));

        btnDisplayCustomer.setText("DisplayCustomer");
        btnDisplayCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisplayCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 120, 70));

        btnNewOrder.setText("New Order");
        btnNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnNewOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 130, 70));

        btnDisplayOrders.setText("Display Orders");
        btnDisplayOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayOrdersActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisplayOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 120, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coffee.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 210, 220));

        btnDisplayCofee1.setText("Display Cofee");
        btnDisplayCofee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayCofee1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisplayCofee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 130, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisplayOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayOrdersActionPerformed
        // TODO add your handling code here:
        DisplayOrders displayOrders = new DisplayOrders();
        // Make the displayOrders window visible
        displayOrders.setVisible(true);
    }//GEN-LAST:event_btnDisplayOrdersActionPerformed

    private void btnDisplayCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayCustomerActionPerformed
        // TODO add your handling code here:
        DisplayCustomer displayCustomer = new DisplayCustomer();
        displayCustomer.setVisible(true);
    }//GEN-LAST:event_btnDisplayCustomerActionPerformed

    private void btnNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderActionPerformed
        // TODO add your handling code here:
        NewOrder newOrder = new NewOrder();
        newOrder.setVisible(true);
    }//GEN-LAST:event_btnNewOrderActionPerformed

    private void btnDisplayCofee1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayCofee1ActionPerformed
        // TODO add your handling code here:
        DisplayCustomer displayCustomer = new DisplayCustomer();
        displayCustomer.setVisible(true);
    }//GEN-LAST:event_btnDisplayCofee1ActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoffeeStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoffeeStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoffeeStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoffeeStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoffeeStore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisplayCofee1;
    private javax.swing.JButton btnDisplayCustomer;
    private javax.swing.JButton btnDisplayOrders;
    private javax.swing.JButton btnNewOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
